name: Attempt buildign the frontend

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run build
